### ISSUE TITLE
Create Memory Bank for Random Problems

### ISSUE THREAD

**Issue by bmlegge** [colemank0259/CTS-285-Group1#4]
*--------------------------------*
As a student, I want to answer random math problems so I can test myself and learn the intended lesson.
*-------------------------------*
- [x] random numbers ranging 1-10 - 1
- [x] random operator - 3
- [x] calculate to compare user entry - 2
- [x] create formula - 2

**Comment by colemank0259** [comment]
MemoryBank.cs is mostly done. I just need to work on input validation for choosing whether to repeat the activity. It will repeat if you type anything other than "2" when prompted, but it's only supposed to repeat if you type "1".

**Comment by Jochs1989** [comment]
Sorry for not being around, I had to pick up my brother from Mississippi. just got back yesterday afternoon. I will look at the memory bank and see whats wrong.

edit: Everything works fine, So i'm assuming brad helped you already the only thing I would change is make the doubles into ints. Then at the top add a Console.Writeline and let the user know to always round down. Makes that last TODO easy to fix and doesn't break agile.

**Comment by colemank0259** [comment]
I just manually merged my changes to the master. Do you guys think the project is ready to submit?

**Comment by Jochs1989** [comment]
I think brad is still finishing his part i'm not sure. Our parts look finished and the menu looks good.
